# Generated by Django 6.0 on 2026-06-03 23:05

from django.db import migrations, models


def default_settings(apps, schema_editor):
    Setting = apps.get_model('recol_setting', 'Recol Setting')

    Setting.objects.get_or_create(default_ui=False)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recol_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_ui', models.BooleanField(default=False, help_text='If set to true it will default to the normal BallsDex UI while still adding the user parameter.')),
            ],
        ),
    ]
